# Generated by Django 2.2.24 on 2021-07-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_word_app', '0002_auto_20210723_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=150, verbose_name='ストップワード')),
            ],
            options={
                'db_table': 'stop_word',
            },
        ),
    ]
